version: "3"

services:

  runtime-setup:
    image: swift-distributed-tracing-baggage:18.04-5.3
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.5-bionic"

  test:
    image: swift-distributed-tracing-baggage:18.04-5.3
    environment: []

  shell:
    image: swift-distributed-tracing-baggage:18.04-5.3
